# Generated by Django 4.2.10 on 2024-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_alter_posts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imageInPage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
